#ifndef SHARED_CONFIG_H
#define SHARED_CONFIG_H

#define DEFAULT_PORT 2002
#define TICKS_PER_SECOND 16

#define MAP_WIDTH 640
#define MAP_HEIGHT 480

#define MAX_PLAYERS 4
#define MAX_BALLS 64

#define SCORE_LOSS_TIME_SECONDS 5
#define SCORE_LOSS_MULTIPLIER 0.9

#define SPEED_TIME_SECONDS 5
#define SPEED_COOLDOWN_SECONDS 5
#define SPEED_MULTIPLIER 1.5
#define DEFAULT_SPEED_TIME_SECONDS -SPEED_COOLDOWN_SECONDS

#define BALL_SPAWN_TIME_SECONDS 2
#define BALL_SCORE 1
#define START_BALLS 32
#define BALL_SIZE 8

#endif
